import type { Product, Testimonial, BlogPost, FaqItem } from './types';

export const placeholderProducts: Product[] = [
  {
    id: '1',
    name: 'Classic Karadant',
    description: 'The original and authentic taste of Gokak, packed with dry fruits and edible gum.',
    price: 250,
    imageUrl: 'https://placehold.co/400x400.png',
    category: 'Karadant',
    sizes: ['250g', '500g', '1kg'],
    ingredients: ['Jaggery', 'Dry Coconut', 'Cashews', 'Almonds', 'Pistachios', 'Edible Gum'],
    nutrition: { 'Calories': '450kcal', 'Protein': '10g', 'Carbs': '50g' },
    rating: 4.8,
    reviewCount: 152,
  },
  {
    id: '2',
    name: 'Antu Laddu',
    description: 'A nutritious and delicious laddu made with edible gum, jaggery, and ghee.',
    price: 300,
    imageUrl: 'https://placehold.co/400x400.png',
    category: 'Laddu',
    sizes: ['500g', '1kg'],
    ingredients: ['Edible Gum', 'Jaggery', 'Ghee', 'Almonds', 'Poppy Seeds'],
    nutrition: { 'Calories': '400kcal', 'Protein': '8g', 'Carbs': '45g' },
    rating: 4.7,
    reviewCount: 98,
  },
  {
    id: '3',
    name: 'Coconut Barfi',
    description: 'Soft, chewy, and melt-in-your-mouth barfi made with fresh coconut and khoya.',
    price: 220,
    imageUrl: 'https://placehold.co/400x400.png',
    category: 'Barfi',
    sizes: ['250g', '500g'],
    ingredients: ['Fresh Coconut', 'Sugar', 'Khoya', 'Cardamom'],
    nutrition: { 'Calories': '350kcal', 'Protein': '5g', 'Carbs': '40g' },
    rating: 4.9,
    reviewCount: 210,
  },
  {
    id: '4',
    name: 'Special Dry Fruit Mix',
    description: 'A premium mix of high-quality dry fruits, perfect for gifting or a healthy snack.',
    price: 450,
    imageUrl: 'https://placehold.co/400x400.png',
    category: 'Special',
    sizes: ['500g'],
    ingredients: ['Cashews', 'Almonds', 'Pistachios', 'Walnuts', 'Raisins'],
    nutrition: { 'Calories': '600kcal', 'Protein': '20g', 'Carbs': '30g' },
    rating: 4.6,
    reviewCount: 75,
  },
  {
    id: '5',
    name: 'Besan Laddu',
    description: 'Classic, fragrant laddus made from roasted gram flour, ghee, and sugar.',
    price: 180,
    imageUrl: 'https://placehold.co/400x400.png',
    category: 'Laddu',
    sizes: ['500g', '1kg'],
    ingredients: ['Gram Flour (Besan)', 'Ghee', 'Sugar', 'Cardamom'],
    nutrition: { 'Calories': '420kcal', 'Protein': '7g', 'Carbs': '55g' },
    rating: 4.5,
    reviewCount: 120,
  },
  {
    id: '6',
    name: 'Sugar-Free Karadant',
    description: 'The great taste of Karadant, specially made for the health-conscious with natural sweeteners.',
    price: 350,
    imageUrl: 'https://placehold.co/400x400.png',
    category: 'Karadant',
    sizes: ['250g', '500g'],
    ingredients: ['Dates', 'Dry Coconut', 'Cashews', 'Almonds', 'Pistachios', 'Edible Gum'],
    nutrition: { 'Calories': '380kcal', 'Protein': '12g', 'Carbs': '40g' },
    rating: 4.8,
    reviewCount: 88,
  },
  {
    id: '7',
    name: 'Kaju Katli',
    description: 'Timeless diamond-shaped cashew fudge, a symbol of celebration.',
    price: 550,
    imageUrl: 'https://placehold.co/400x400.png',
    category: 'Barfi',
    sizes: ['250g', '500g'],
    ingredients: ['Cashews', 'Sugar', 'Ghee', 'Silver Leaf'],
    nutrition: { 'Calories': '500kcal', 'Protein': '15g', 'Carbs': '48g' },
    rating: 4.9,
    reviewCount: 300,
  },
  {
    id: '8',
    name: 'Gokak Special Peda',
    description: 'A regional specialty, this milk-based sweet is soft, creamy, and mildly sweet.',
    price: 280,
    imageUrl: 'https://placehold.co/400x400.png',
    category: 'Special',
    sizes: ['500g'],
    ingredients: ['Milk', 'Khoya', 'Sugar', 'Saffron'],
    nutrition: { 'Calories': '320kcal', 'Protein': '9g', 'Carbs': '35g' },
    rating: 4.7,
    reviewCount: 115,
  },
];

export const placeholderTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    location: 'Bengaluru, KA',
    avatarUrl: 'https://placehold.co/100x100.png',
    rating: 5,
    text: 'The most authentic Karadant I have ever had outside of Gokak! The taste is just perfect, and the delivery was super fast. Highly recommended!',
  },
  {
    id: '2',
    name: 'Rahul Desai',
    location: 'Mumbai, MH',
    avatarUrl: 'https://placehold.co/100x100.png',
    rating: 5,
    text: 'I ordered the Antu Laddu and Coconut Barfi for a family function. Everyone loved it. The quality and freshness are unmatched. Will order again.',
  },
  {
    id: '3',
    name: 'Anjali Menon',
    location: 'Chennai, TN',
    avatarUrl: 'https://placehold.co/100x100.png',
    rating: 4,
    text: 'Great products and beautiful packaging. The website is easy to use. I just wish they had more sugar-free options. Overall, a great experience.',
  },
];

export const placeholderBlogPosts: BlogPost[] = [
    {
        id: '1',
        slug: 'history-of-karadant',
        title: 'The Royal History of Karadant: A Sweet from Gokak',
        excerpt: 'Dive into the rich history of Karadant, a delicacy that has been cherished for generations in Karnataka. Learn about its origins and what makes it so special.',
        content: '<p>Full blog post content goes here...</p>',
        imageUrl: 'https://placehold.co/800x600.png',
        author: 'Team Janata',
        date: '2024-07-15',
    },
    {
        id: '2',
        slug: 'health-benefits-of-edible-gum',
        title: 'The Surprising Health Benefits of Edible Gum (Antu)',
        excerpt: 'Edible gum, or Antu, is a key ingredient in many of our sweets. Discover the incredible health benefits of this traditional superfood.',
        content: '<p>Full blog post content goes here...</p>',
        imageUrl: 'https://placehold.co/800x600.png',
        author: 'Team Janata',
        date: '2024-07-01',
    },
    {
        id: '3',
        slug: 'perfect-sweet-for-every-occasion',
        title: 'Pairing the Perfect Sweet for Every Occasion',
        excerpt: 'From festivals to family gatherings, find out which of our traditional sweets is the perfect fit for your next celebration.',
        content: '<p>Full blog post content goes here...</p>',
        imageUrl: 'https://placehold.co/800x600.png',
        author: 'Team Janata',
        date: '2024-06-20',
    },
];

export const placeholderFaqs: FaqItem[] = [
  {
    question: 'What is Karadant?',
    answer: 'Karadant is a traditional Indian sweet from Gokak, Karnataka. It is a nutritious delicacy made from a mixture of jaggery, dried fruits, nuts, and edible gum (Antu). It\'s known for its unique chewy texture and rich flavor.',
  },
  {
    question: 'What is the shelf life of your sweets?',
    answer: 'Most of our sweets, including Karadant, have a shelf life of 2-3 weeks when stored in a cool, dry place in an airtight container. Please check the product page for specific details.',
  },
  {
    question: 'Do you offer bulk orders for events or corporate gifting?',
    answer: 'Yes, we do! We provide special pricing and packaging for bulk orders for weddings, events, and corporate gifting. Please visit our "Bulk Orders" section or contact us directly for inquiries.',
  },
  {
    question: 'Do you ship across India?',
    answer: 'Yes, we ship our products to most locations across India. Shipping times and charges may vary based on the delivery address.',
  },
  {
    question: 'Are your products vegetarian?',
    answer: 'Yes, all our products are 100% vegetarian.',
  },
  {
    question: 'Do you have sugar-free options?',
    answer: 'Yes, we have a Sugar-Free Karadant option that is made with natural sweeteners like dates. You can find it in our product catalog.',
  },
];
